version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.58.3

    steps:
      - checkout
      - run:
          name: "Change to example site directory"
          command: cd exampleSite
      - run:
          name: "Run hugo against default config"
          command: HUGO_ENV=production hugo -v -d workspace/public


workflows:
  version: 2
  build-test:
    jobs:
      - build
